### ISSUE TITLE
Explain what this source does

### ISSUE THREAD

**Issue by SmiteshP** [hrsh7th/cmp-nvim-lua#1]
It isn't clear what this source is for? Please consider adding a readme for this.

**Comment by hrsh7th** [comment]
I may not understand what to do.

What kind of explanation would you like to have?

(google translated)

**Comment by SmiteshP** [comment]
Like cmp-vsnip adds functionality for vsnip, I was confused as to what does this source do?

**Comment by hrsh7th** [comment]
This source will complete neovim runtime lua API. OK I will update README.md.

**Comment by hrsh7th** [comment]
I've added README.md. Thanks. https://github.com/hrsh7th/cmp-nvim-lua/commit/9736b19548e6c06a0b966b4ce326a2d724df501c
