### ISSUE TITLE
Enum completion causes error

### ISSUE THREAD

**Issue by eruizc-dev** [hrsh7th/cmp-nvim-lua#4]
When attempting to complete `vim.diagnostic.severity.ERROR` an error pops up:

```
Error executing vim.schedule lua callback: /.config/nvim/plugged/nvim-cmp/lua/cmp/utils/str.lua:82: attempt to get length of local 'text' (a number value)
```
![image](https://user-images.githubusercontent.com/58179604/136718625-0bde9abe-c165-417c-bf60-64a8b2f71046.png)

**Comment by hrsh7th** [comment]
Fixed
https://github.com/hrsh7th/cmp-nvim-lua/commit/d276254e7198ab7d00f117e88e223b4bd8c02d21
