### ISSUE TITLE
include documentation

### ISSUE THREAD

**Issue by FelipeLema** [hrsh7th/cmp-nvim-lua#7]
I dunno if you can access the documentation of a function in lua, but at least we can use the official nvim documentation to dig it up (although some parsing would be involved)

**Comment by FelipeLema** [comment]
looks like accessing the docstring from within lua is a no go according to this [stackoverflow QA / discussion](https://stackoverflow.com/questions/10902079/lua-reflection-function-parameters-and-docstrings)

**Comment by hrsh7th** [comment]
I didn't plan it... Sorry.
If you have solid solution, feel free to re-open it.
